//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace Web.Client.Api
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IClient
    {
        /// <summary>
        /// List tasks with pagination and optional filters
        /// </summary>
        /// <remarks>
        /// フロント（docs/tasks-show.md）向け表示ロジック。
        /// <br/>実装手順:
        /// <br/>  1. クエリ q（title, content の全文検索）、tag（カンマ区切り）、completed（真偽）、sort、page、pageSize を受け取る。
        /// <br/>  2. DB でフィルタ・全文検索・ソートを適用し、該当アイテムを取得する（Postgres の全文検索利用が推奨）。
        /// <br/>  3. 合計件数 total を取得して TaskList { items, total, page, pageSize } を返す。
        /// <br/>  4. UI 要件として「全項目を1画面に表示（スクロール不可）」という記述があるため、pageSize の調整やフロント側での表示制御を想定する。
        /// <br/>注意:
        /// <br/>  - 大量データ時は pageSize 制限、インデックス、検索分割を検討する。
        /// </remarks>
        /// <param name="q">Full-text search over title and content</param>
        /// <param name="tag">Filter by tag (comma-separated)</param>
        /// <param name="completed">Filter by completion status</param>
        /// <param name="sort">Sort field (e.g. dueDate or createdAt). Prefix with '-' for descending.</param>
        /// <param name="page">Page number (1-based)</param>
        /// <param name="pageSize">Items per page</param>
        /// <returns>A paginated list of tasks</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TaskList> ListTasksAsync(string q, string tag, bool? completed, string sort, int? page, int? pageSize);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List tasks with pagination and optional filters
        /// </summary>
        /// <remarks>
        /// フロント（docs/tasks-show.md）向け表示ロジック。
        /// <br/>実装手順:
        /// <br/>  1. クエリ q（title, content の全文検索）、tag（カンマ区切り）、completed（真偽）、sort、page、pageSize を受け取る。
        /// <br/>  2. DB でフィルタ・全文検索・ソートを適用し、該当アイテムを取得する（Postgres の全文検索利用が推奨）。
        /// <br/>  3. 合計件数 total を取得して TaskList { items, total, page, pageSize } を返す。
        /// <br/>  4. UI 要件として「全項目を1画面に表示（スクロール不可）」という記述があるため、pageSize の調整やフロント側での表示制御を想定する。
        /// <br/>注意:
        /// <br/>  - 大量データ時は pageSize 制限、インデックス、検索分割を検討する。
        /// </remarks>
        /// <param name="q">Full-text search over title and content</param>
        /// <param name="tag">Filter by tag (comma-separated)</param>
        /// <param name="completed">Filter by completion status</param>
        /// <param name="sort">Sort field (e.g. dueDate or createdAt). Prefix with '-' for descending.</param>
        /// <param name="page">Page number (1-based)</param>
        /// <param name="pageSize">Items per page</param>
        /// <returns>A paginated list of tasks</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<TaskList> ListTasksAsync(string q, string tag, bool? completed, string sort, int? page, int? pageSize, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Create a new task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-add.md）からの新規作成処理。
        /// <br/>実装手順:
        /// <br/>  1. リクエスト body (TaskCreate) をバリデーション（title 必須）する。
        /// <br/>  2. id を GUID 生成、createdAt を現在時刻に設定、completed を既定値 false に設定する。
        /// <br/>  3. DB に挿入し、201 を返す。可能なら Location ヘッダに /tasks/{id} を設定する。
        /// <br/>  4. 入力不正時は 400 を返す。
        /// </remarks>
        /// <param name="body">新規作成するタスクのペイロード</param>
        /// <returns>Task created</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> CreateTaskAsync(TaskCreate body);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Create a new task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-add.md）からの新規作成処理。
        /// <br/>実装手順:
        /// <br/>  1. リクエスト body (TaskCreate) をバリデーション（title 必須）する。
        /// <br/>  2. id を GUID 生成、createdAt を現在時刻に設定、completed を既定値 false に設定する。
        /// <br/>  3. DB に挿入し、201 を返す。可能なら Location ヘッダに /tasks/{id} を設定する。
        /// <br/>  4. 入力不正時は 400 を返す。
        /// </remarks>
        /// <param name="body">新規作成するタスクのペイロード</param>
        /// <returns>Task created</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> CreateTaskAsync(TaskCreate body, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Get a single task by ID
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. path の taskId（UUID）で DB を検索し、存在すれば Task を返す。
        /// <br/>  2. 存在しない場合は 404 を返す（#/components/responses/NotFound を利用）。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task found</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> GetTaskAsync(string taskId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get a single task by ID
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. path の taskId（UUID）で DB を検索し、存在すれば Task を返す。
        /// <br/>  2. 存在しない場合は 404 を返す（#/components/responses/NotFound を利用）。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task found</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> GetTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Replace a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId のタスクを全件置換する（全体更新）。
        /// <br/>  2. createdAt は保持し、updatedAt を現在時刻に更新する。
        /// <br/>  3. バリデーション失敗は 400、タスク未発見は 404 を返す。
        /// </remarks>
        /// <param name="body">タスクの全体置換ペイロード（title 必須）</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task replaced</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> ReplaceTaskAsync(TaskCreate body, string taskId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Replace a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId のタスクを全件置換する（全体更新）。
        /// <br/>  2. createdAt は保持し、updatedAt を現在時刻に更新する。
        /// <br/>  3. バリデーション失敗は 400、タスク未発見は 404 を返す。
        /// </remarks>
        /// <param name="body">タスクの全体置換ペイロード（title 必須）</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task replaced</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> ReplaceTaskAsync(TaskCreate body, string taskId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Update one or more fields on a task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-update.md）の要件に合わせた部分更新。
        /// <br/>実装手順:
        /// <br/>  1. 提供されたフィールドのみ更新し、updatedAt を現在時刻に更新する（部分更新）。
        /// <br/>  2. contenteditable によるインライン編集を想定し、頻繁な小さな更新に耐えられるようにする。
        /// <br/>  3. 存在しない場合は 404 を返す。
        /// </remarks>
        /// <param name="body">部分更新するフィールドを含むペイロード</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> UpdateTaskAsync(TaskUpdate body, string taskId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Update one or more fields on a task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-update.md）の要件に合わせた部分更新。
        /// <br/>実装手順:
        /// <br/>  1. 提供されたフィールドのみ更新し、updatedAt を現在時刻に更新する（部分更新）。
        /// <br/>  2. contenteditable によるインライン編集を想定し、頻繁な小さな更新に耐えられるようにする。
        /// <br/>  3. 存在しない場合は 404 を返す。
        /// </remarks>
        /// <param name="body">部分更新するフィールドを含むペイロード</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> UpdateTaskAsync(TaskUpdate body, string taskId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Delete a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId を削除する。成功時は 204 を返す。
        /// <br/>  2. タスク未発見なら 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task deleted (no content)</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task DeleteTaskAsync(string taskId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Delete a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId を削除する。成功時は 204 を返す。
        /// <br/>  2. タスク未発見なら 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task deleted (no content)</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task DeleteTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Mark a task as completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を true に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> CompleteTaskAsync(string taskId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Mark a task as completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を true に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> CompleteTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken);

        /// <summary>
        /// Mark a task as not completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を false に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> UncompleteTaskAsync(string taskId);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Mark a task as not completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を false に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Task> UncompleteTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Client : System.Object, IClient
    {
        #pragma warning disable 8618
        private string _baseUrl;
        #pragma warning restore 8618

        private System.Net.Http.HttpClient _httpClient;
        private static System.Lazy<System.Text.Json.JsonSerializerOptions> _settings = new System.Lazy<System.Text.Json.JsonSerializerOptions>(CreateSerializerSettings, true);
        private System.Text.Json.JsonSerializerOptions _instanceSettings;

    #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public Client(System.Net.Http.HttpClient httpClient)
    #pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            BaseUrl = "http://localhost:5000";
            _httpClient = httpClient;
            Initialize();
        }

        private static System.Text.Json.JsonSerializerOptions CreateSerializerSettings()
        {
            var settings = new System.Text.Json.JsonSerializerOptions();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        public string BaseUrl
        {
            get { return _baseUrl; }
            set
            {
                _baseUrl = value;
                if (!string.IsNullOrEmpty(_baseUrl) && !_baseUrl.EndsWith("/"))
                    _baseUrl += '/';
            }
        }

        protected System.Text.Json.JsonSerializerOptions JsonSerializerSettings { get { return _instanceSettings ?? _settings.Value; } }

        static partial void UpdateJsonSerializerSettings(System.Text.Json.JsonSerializerOptions settings);

        partial void Initialize();

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <summary>
        /// List tasks with pagination and optional filters
        /// </summary>
        /// <remarks>
        /// フロント（docs/tasks-show.md）向け表示ロジック。
        /// <br/>実装手順:
        /// <br/>  1. クエリ q（title, content の全文検索）、tag（カンマ区切り）、completed（真偽）、sort、page、pageSize を受け取る。
        /// <br/>  2. DB でフィルタ・全文検索・ソートを適用し、該当アイテムを取得する（Postgres の全文検索利用が推奨）。
        /// <br/>  3. 合計件数 total を取得して TaskList { items, total, page, pageSize } を返す。
        /// <br/>  4. UI 要件として「全項目を1画面に表示（スクロール不可）」という記述があるため、pageSize の調整やフロント側での表示制御を想定する。
        /// <br/>注意:
        /// <br/>  - 大量データ時は pageSize 制限、インデックス、検索分割を検討する。
        /// </remarks>
        /// <param name="q">Full-text search over title and content</param>
        /// <param name="tag">Filter by tag (comma-separated)</param>
        /// <param name="completed">Filter by completion status</param>
        /// <param name="sort">Sort field (e.g. dueDate or createdAt). Prefix with '-' for descending.</param>
        /// <param name="page">Page number (1-based)</param>
        /// <param name="pageSize">Items per page</param>
        /// <returns>A paginated list of tasks</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<TaskList> ListTasksAsync(string q, string tag, bool? completed, string sort, int? page, int? pageSize)
        {
            return ListTasksAsync(q, tag, completed, sort, page, pageSize, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// List tasks with pagination and optional filters
        /// </summary>
        /// <remarks>
        /// フロント（docs/tasks-show.md）向け表示ロジック。
        /// <br/>実装手順:
        /// <br/>  1. クエリ q（title, content の全文検索）、tag（カンマ区切り）、completed（真偽）、sort、page、pageSize を受け取る。
        /// <br/>  2. DB でフィルタ・全文検索・ソートを適用し、該当アイテムを取得する（Postgres の全文検索利用が推奨）。
        /// <br/>  3. 合計件数 total を取得して TaskList { items, total, page, pageSize } を返す。
        /// <br/>  4. UI 要件として「全項目を1画面に表示（スクロール不可）」という記述があるため、pageSize の調整やフロント側での表示制御を想定する。
        /// <br/>注意:
        /// <br/>  - 大量データ時は pageSize 制限、インデックス、検索分割を検討する。
        /// </remarks>
        /// <param name="q">Full-text search over title and content</param>
        /// <param name="tag">Filter by tag (comma-separated)</param>
        /// <param name="completed">Filter by completion status</param>
        /// <param name="sort">Sort field (e.g. dueDate or createdAt). Prefix with '-' for descending.</param>
        /// <param name="page">Page number (1-based)</param>
        /// <param name="pageSize">Items per page</param>
        /// <returns>A paginated list of tasks</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<TaskList> ListTasksAsync(string q, string tag, bool? completed, string sort, int? page, int? pageSize, System.Threading.CancellationToken cancellationToken)
        {
            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks"
                    urlBuilder_.Append("tasks");
                    urlBuilder_.Append('?');
                    if (q != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("q")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(q, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (tag != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("tag")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(tag, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (completed != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("completed")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(completed, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (sort != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("sort")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(sort, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (page != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("page")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(page, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (pageSize != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("pageSize")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(pageSize, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<TaskList>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Create a new task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-add.md）からの新規作成処理。
        /// <br/>実装手順:
        /// <br/>  1. リクエスト body (TaskCreate) をバリデーション（title 必須）する。
        /// <br/>  2. id を GUID 生成、createdAt を現在時刻に設定、completed を既定値 false に設定する。
        /// <br/>  3. DB に挿入し、201 を返す。可能なら Location ヘッダに /tasks/{id} を設定する。
        /// <br/>  4. 入力不正時は 400 を返す。
        /// </remarks>
        /// <param name="body">新規作成するタスクのペイロード</param>
        /// <returns>Task created</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<Task> CreateTaskAsync(TaskCreate body)
        {
            return CreateTaskAsync(body, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Create a new task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-add.md）からの新規作成処理。
        /// <br/>実装手順:
        /// <br/>  1. リクエスト body (TaskCreate) をバリデーション（title 必須）する。
        /// <br/>  2. id を GUID 生成、createdAt を現在時刻に設定、completed を既定値 false に設定する。
        /// <br/>  3. DB に挿入し、201 を返す。可能なら Location ヘッダに /tasks/{id} を設定する。
        /// <br/>  4. 入力不正時は 400 を返す。
        /// </remarks>
        /// <param name="body">新規作成するタスクのペイロード</param>
        /// <returns>Task created</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Task> CreateTaskAsync(TaskCreate body, System.Threading.CancellationToken cancellationToken)
        {
            if (body == null)
                throw new System.ArgumentNullException("body");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    var json_ = System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(body, JsonSerializerSettings);
                    var content_ = new System.Net.Http.ByteArrayContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks"
                    urlBuilder_.Append("tasks");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 201)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Task>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 400)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Invalid input", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Get a single task by ID
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. path の taskId（UUID）で DB を検索し、存在すれば Task を返す。
        /// <br/>  2. 存在しない場合は 404 を返す（#/components/responses/NotFound を利用）。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task found</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<Task> GetTaskAsync(string taskId)
        {
            return GetTaskAsync(taskId, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Get a single task by ID
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. path の taskId（UUID）で DB を検索し、存在すれば Task を返す。
        /// <br/>  2. 存在しない場合は 404 を返す（#/components/responses/NotFound を利用）。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task found</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Task> GetTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken)
        {
            if (taskId == null)
                throw new System.ArgumentNullException("taskId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks/{taskId}"
                    urlBuilder_.Append("tasks/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(taskId, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Task>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Resource not found", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Replace a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId のタスクを全件置換する（全体更新）。
        /// <br/>  2. createdAt は保持し、updatedAt を現在時刻に更新する。
        /// <br/>  3. バリデーション失敗は 400、タスク未発見は 404 を返す。
        /// </remarks>
        /// <param name="body">タスクの全体置換ペイロード（title 必須）</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task replaced</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<Task> ReplaceTaskAsync(TaskCreate body, string taskId)
        {
            return ReplaceTaskAsync(body, taskId, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Replace a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId のタスクを全件置換する（全体更新）。
        /// <br/>  2. createdAt は保持し、updatedAt を現在時刻に更新する。
        /// <br/>  3. バリデーション失敗は 400、タスク未発見は 404 を返す。
        /// </remarks>
        /// <param name="body">タスクの全体置換ペイロード（title 必須）</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task replaced</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Task> ReplaceTaskAsync(TaskCreate body, string taskId, System.Threading.CancellationToken cancellationToken)
        {
            if (taskId == null)
                throw new System.ArgumentNullException("taskId");

            if (body == null)
                throw new System.ArgumentNullException("body");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    var json_ = System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(body, JsonSerializerSettings);
                    var content_ = new System.Net.Http.ByteArrayContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("PUT");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks/{taskId}"
                    urlBuilder_.Append("tasks/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(taskId, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Task>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 400)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Bad request", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Resource not found", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Update one or more fields on a task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-update.md）の要件に合わせた部分更新。
        /// <br/>実装手順:
        /// <br/>  1. 提供されたフィールドのみ更新し、updatedAt を現在時刻に更新する（部分更新）。
        /// <br/>  2. contenteditable によるインライン編集を想定し、頻繁な小さな更新に耐えられるようにする。
        /// <br/>  3. 存在しない場合は 404 を返す。
        /// </remarks>
        /// <param name="body">部分更新するフィールドを含むペイロード</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<Task> UpdateTaskAsync(TaskUpdate body, string taskId)
        {
            return UpdateTaskAsync(body, taskId, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Update one or more fields on a task
        /// </summary>
        /// <remarks>
        /// フロント（docs/task-update.md）の要件に合わせた部分更新。
        /// <br/>実装手順:
        /// <br/>  1. 提供されたフィールドのみ更新し、updatedAt を現在時刻に更新する（部分更新）。
        /// <br/>  2. contenteditable によるインライン編集を想定し、頻繁な小さな更新に耐えられるようにする。
        /// <br/>  3. 存在しない場合は 404 を返す。
        /// </remarks>
        /// <param name="body">部分更新するフィールドを含むペイロード</param>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Task> UpdateTaskAsync(TaskUpdate body, string taskId, System.Threading.CancellationToken cancellationToken)
        {
            if (taskId == null)
                throw new System.ArgumentNullException("taskId");

            if (body == null)
                throw new System.ArgumentNullException("body");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    var json_ = System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(body, JsonSerializerSettings);
                    var content_ = new System.Net.Http.ByteArrayContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("PATCH");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks/{taskId}"
                    urlBuilder_.Append("tasks/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(taskId, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Task>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 400)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Bad request", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Resource not found", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Delete a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId を削除する。成功時は 204 を返す。
        /// <br/>  2. タスク未発見なら 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task deleted (no content)</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task DeleteTaskAsync(string taskId)
        {
            return DeleteTaskAsync(taskId, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Delete a task
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId を削除する。成功時は 204 を返す。
        /// <br/>  2. タスク未発見なら 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task deleted (no content)</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task DeleteTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken)
        {
            if (taskId == null)
                throw new System.ArgumentNullException("taskId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("DELETE");

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks/{taskId}"
                    urlBuilder_.Append("tasks/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(taskId, System.Globalization.CultureInfo.InvariantCulture)));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 204)
                        {
                            return;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Resource not found", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Mark a task as completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を true に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<Task> CompleteTaskAsync(string taskId)
        {
            return CompleteTaskAsync(taskId, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Mark a task as completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を true に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Task> CompleteTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken)
        {
            if (taskId == null)
                throw new System.ArgumentNullException("taskId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Content = new System.Net.Http.StringContent(string.Empty, System.Text.Encoding.UTF8, "application/json");
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks/{taskId}/complete"
                    urlBuilder_.Append("tasks/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(taskId, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append("/complete");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Task>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Resource not found", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Mark a task as not completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を false に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<Task> UncompleteTaskAsync(string taskId)
        {
            return UncompleteTaskAsync(taskId, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Mark a task as not completed
        /// </summary>
        /// <remarks>
        /// 実装手順:
        /// <br/>  1. 指定 taskId の Completed を false に設定し、updatedAt を更新する。
        /// <br/>  2. 更新後の Task を返す。未発見は 404 を返す。
        /// </remarks>
        /// <param name="taskId">タスクID（UUID）</param>
        /// <returns>Task updated</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<Task> UncompleteTaskAsync(string taskId, System.Threading.CancellationToken cancellationToken)
        {
            if (taskId == null)
                throw new System.ArgumentNullException("taskId");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Content = new System.Net.Http.StringContent(string.Empty, System.Text.Encoding.UTF8, "application/json");
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                    if (!string.IsNullOrEmpty(_baseUrl)) urlBuilder_.Append(_baseUrl);
                    // Operation Path: "tasks/{taskId}/uncomplete"
                    urlBuilder_.Append("tasks/");
                    urlBuilder_.Append(System.Uri.EscapeDataString(ConvertToString(taskId, System.Globalization.CultureInfo.InvariantCulture)));
                    urlBuilder_.Append("/uncomplete");

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Task>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        if (status_ == 404)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<Error>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            throw new ApiException<Error>("Resource not found", status_, objectResponse_.Text, headers_, objectResponse_.Object, null);
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText)
            {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<string> ReadAsStringAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStringAsync(cancellationToken);
    #else
            return content.ReadAsStringAsync();
    #endif
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<System.IO.Stream> ReadAsStreamAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStreamAsync(cancellationToken);
    #else
            return content.ReadAsStreamAsync();
    #endif
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
            {
                return new ObjectResponseResult<T>(default(T), string.Empty);
            }

            if (ReadResponseAsString)
            {
                var responseText = await ReadAsStringAsync(response.Content, cancellationToken).ConfigureAwait(false);
                try
                {
                    var typedBody = System.Text.Json.JsonSerializer.Deserialize<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using (var responseStream = await ReadAsStreamAsync(response.Content, cancellationToken).ConfigureAwait(false))
                    {
                        var typedBody = await System.Text.Json.JsonSerializer.DeserializeAsync<T>(responseStream, JsonSerializerSettings, cancellationToken).ConfigureAwait(false);
                        return new ObjectResponseResult<T>(typedBody, string.Empty);
                    }
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null)
            {
                return "";
            }

            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field_ = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field_ != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field_, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool) 
            {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            }
            else if (value is byte[])
            {
                return System.Convert.ToBase64String((byte[]) value);
            }
            else if (value is string[])
            {
                return string.Join(",", (string[])value);
            }
            else if (value.GetType().IsArray)
            {
                var valueArray = (System.Array)value;
                var valueTextArray = new string[valueArray.Length];
                for (var i = 0; i < valueArray.Length; i++)
                {
                    valueTextArray[i] = ConvertToString(valueArray.GetValue(i), cultureInfo);
                }
                return string.Join(",", valueTextArray);
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    /// <summary>
    /// タスク情報（取得・更新・削除対象）
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Task
    {

        /// <summary>
        /// タスクID（UUID）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.Guid Id { get; set; }

        /// <summary>
        /// タスクタイトル
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; }

        /// <summary>
        /// タスクの詳細（任意）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public string Content { get; set; }

        /// <summary>
        /// 期日（ISO 8601）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dueDate")]
        public System.DateTimeOffset? DueDate { get; set; }

        /// <summary>
        /// 完了フラグ（true=完了）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("completed")]
        public bool Completed { get; set; } = false;

        /// <summary>
        /// タグ一覧
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("tags")]
        public System.Collections.Generic.ICollection<string> Tags { get; set; }

        /// <summary>
        /// 作成日時（ISO 8601）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("createdAt")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTimeOffset CreatedAt { get; set; }

        /// <summary>
        /// 更新日時（ISO 8601、未更新時は null）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("updatedAt")]
        public System.DateTimeOffset? UpdatedAt { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// タスク作成・全体置換リクエスト（title 必須、それ以外は任意）
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TaskCreate
    {

        /// <summary>
        /// タイトル（必須）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("title")]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Title { get; set; }

        /// <summary>
        /// タスクの詳細
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public string Content { get; set; }

        /// <summary>
        /// 期日（ISO 8601）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dueDate")]
        public System.DateTimeOffset DueDate { get; set; }

        /// <summary>
        /// タグ一覧
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("tags")]
        public System.Collections.Generic.ICollection<string> Tags { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// タスク部分更新リクエスト（全フィールド任意、指定されたフィールドのみ更新される）
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TaskUpdate
    {

        /// <summary>
        /// タイトル
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// タスクの詳細
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public string Content { get; set; }

        /// <summary>
        /// 期日（ISO 8601）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("dueDate")]
        public System.DateTimeOffset DueDate { get; set; }

        /// <summary>
        /// 完了フラグ（true=完了）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("completed")]
        public bool Completed { get; set; }

        /// <summary>
        /// タグ一覧
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("tags")]
        public System.Collections.Generic.ICollection<string> Tags { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// ページネーション対応のタスク一覧レスポンス
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TaskList
    {

        /// <summary>
        /// タスク配列
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("items")]
        public System.Collections.Generic.ICollection<Task> Items { get; set; }

        /// <summary>
        /// 合計件数
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("total")]
        public int Total { get; set; }

        /// <summary>
        /// 現在ページ番号（1-based）
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("page")]
        public int Page { get; set; }

        /// <summary>
        /// 1ページあたりの件数
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pageSize")]
        public int PageSize { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// エラーレスポンス（code と message を含む）
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Error
    {

        /// <summary>
        /// エラーコード
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public int Code { get; set; }

        /// <summary>
        /// エラーメッセージ
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("message")]
        public string Message { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException
    {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765